gitlab-server:
  #ports:
  #  - ${ssh_port}:22/tcp
  #  - ${http_port}:80/tcp
  #  - ${https_port}:443/tcp
  privileged: true
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:9.5.6-ce.0
  volumes:
    - /gitlab/etc/gitlab:/etc/gitlab
    - /gitlab/var/log/gitlab:/var/log/gitlab
    - /gitlab/var/opt/gitlab:/var/opt/gitlab
    #- /certs/production/certs/${certificate_name}/fullchain.pem:/etc/gitlab/ssl/${gitlab_hostname}.crt
    #- /certs/production/certs/${certificate_name}/privkey.pem:/etc/gitlab/ssl/${gitlab_hostname}.key
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'